// <auto-generated />
using System;
using Ecu911.BibliotecaService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecu911.BibliotecaService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401204747_FinalBiblioteca")]
    partial class FinalBiblioteca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaArchivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibliotecaDocumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BibliotecaDocumentoId")
                        .IsUnique();

                    b.ToTable("BibliotecaArchivos");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BibliotecaCategorias");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaColeccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("BIBLIOTECA_VIRTUAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrganizationalUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationalUnitId");

                    b.HasIndex("ParentId");

                    b.ToTable("BibliotecaColeccions");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaDescarga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibliotecaArchivoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibliotecaDocumentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DownloadedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BibliotecaArchivoId");

                    b.HasIndex("BibliotecaDocumentoId");

                    b.ToTable("BibliotecaDescargas");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibliotecaCategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BibliotecaColeccionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BibliotecaCategoriaId");

                    b.HasIndex("BibliotecaColeccionId");

                    b.ToTable("BibliotecaDocumentos");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibliotecaColeccionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDownload")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManage")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUpload")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationalUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationalUnitId");

                    b.HasIndex("BibliotecaColeccionId", "OrganizationalUnitId")
                        .IsUnique();

                    b.ToTable("BibliotecaPermisos");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.OrganizationalUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("OrganizationalUnits");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaArchivo", b =>
                {
                    b.HasOne("Ecu911.BibliotecaService.Models.BibliotecaDocumento", "BibliotecaDocumento")
                        .WithOne("BibliotecaArchivo")
                        .HasForeignKey("Ecu911.BibliotecaService.Models.BibliotecaArchivo", "BibliotecaDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BibliotecaDocumento");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaColeccion", b =>
                {
                    b.HasOne("Ecu911.BibliotecaService.Models.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany()
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ecu911.BibliotecaService.Models.BibliotecaColeccion", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrganizationalUnit");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaDescarga", b =>
                {
                    b.HasOne("Ecu911.BibliotecaService.Models.BibliotecaArchivo", "BibliotecaArchivo")
                        .WithMany("BibliotecaDescargas")
                        .HasForeignKey("BibliotecaArchivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ecu911.BibliotecaService.Models.BibliotecaDocumento", "BibliotecaDocumento")
                        .WithMany("BibliotecaDescargas")
                        .HasForeignKey("BibliotecaDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BibliotecaArchivo");

                    b.Navigation("BibliotecaDocumento");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaDocumento", b =>
                {
                    b.HasOne("Ecu911.BibliotecaService.Models.BibliotecaCategoria", "BibliotecaCategoria")
                        .WithMany("BibliotecaDocumentos")
                        .HasForeignKey("BibliotecaCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecu911.BibliotecaService.Models.BibliotecaColeccion", "BibliotecaColeccion")
                        .WithMany()
                        .HasForeignKey("BibliotecaColeccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BibliotecaCategoria");

                    b.Navigation("BibliotecaColeccion");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaPermiso", b =>
                {
                    b.HasOne("Ecu911.BibliotecaService.Models.BibliotecaColeccion", "BibliotecaColeccion")
                        .WithMany()
                        .HasForeignKey("BibliotecaColeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ecu911.BibliotecaService.Models.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany()
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BibliotecaColeccion");

                    b.Navigation("OrganizationalUnit");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.OrganizationalUnit", b =>
                {
                    b.HasOne("Ecu911.BibliotecaService.Models.OrganizationalUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaArchivo", b =>
                {
                    b.Navigation("BibliotecaDescargas");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaCategoria", b =>
                {
                    b.Navigation("BibliotecaDocumentos");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaColeccion", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.BibliotecaDocumento", b =>
                {
                    b.Navigation("BibliotecaArchivo");

                    b.Navigation("BibliotecaDescargas");
                });

            modelBuilder.Entity("Ecu911.BibliotecaService.Models.OrganizationalUnit", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
